
# SEO settings
title: "Exploring Possibilities for Open Data Standards"
description: "A catalog of projects that demonstrate the value of open data standards"
keywords: "open, data, sunlight, standards, free, civic, innovation, engagement, technology, tech"
url: http://github.com/sunlightpolicy/open_data_standards_project
baseurl: "" # apply repo name if use it under gh-pages branch
# baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-48789618-8
repo: http://github.com/sunlightpolicy/open_data_standards_project

# Build settings
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Andrew Yaspan"
  job      : "Computational Analysis and Public Policy Student"
  thumb    : /images/author.jpg
  email    : ayaspan@sunlightfoundation.com
  github   : http://github.com/aycrazy
  twitter  : http://twitter.com/andrewyaspan

# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@andrewyaspan"

#api keys

plugins:
  - bourbon
  - jekyll-paginate

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
